name: CI for Pushes and Pull Requests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest


    # Source: Tutorial in Github documentation. 
    # Link: https://docs.github.com/en/actions/tutorials/use-containerized-services/create-postgresql-service-containers
    # Create service containers
    services:
      postgres:
        image: postgres

        # Provide the postgres instance credentials
        env:
          POSTGRES_DB: test-db
          POSTGRES_USER: test-user
          POSTGRES_PASSWORD: test-pw

        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5



    steps:
      - name: Checkout the repository code
        uses: actions/checkout@v5

      - name: Setup node.js
        uses: actions/setup-node@v5

      - name: Install all, i guess
        run: npm run install:all
      
      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      - name: Run the linter
        run: npm run lint:backend

      # Run tests using the connection URL for the postgres instance in this Actions workflow
      - name: Run the tests
        env:
          DATABASE_URL: postgresql://test-user:test-pw@localhost:5432/test-db
          # NODE_ENV: test
        run: npm run test:backend

